accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:account_pk>/', views.detail, name='detail'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:account_pk>/follow/', views.follow, name='follow'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/',views.detail,name='detail'),
    path('<int:movie_pk>/reviews/new/',views.new,name='new'),
    path('<int:movie_pk>/reviews/<int:review_pk>/delete/',views.delete,name='delete'),
    path('<int:movie_pk>/like/',views.like,name='like'),
]

pjt10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls'))
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='followings',
        blank=True
    )

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20)

class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    genres = models.ManyToManyField(
        Genre, 
        related_name='movies',
        blank=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="like_movies",
        blank=True
    )

class Review(models.Model):
    content = models.CharField(max_length=140)
    score = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username',)

movies/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user','movie')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import User
from .forms import CustomUserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model

def index(request):
    accounts = User.objects.all()
    context = {
        'accounts': accounts
    }
    return render(request, 'accounts/index.html', context)

def detail(request, account_pk):
    account = get_object_or_404(User, id=account_pk)
    context = {
        'account': account
    }
    return render(request, 'accounts/profile.html', context)

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('movies:index')

def follow(request, account_pk):
    user_profile = get_object_or_404(get_user_model(), pk=account_pk)
    if request.user in user_profile.followers.all(): 
        user_profile.followers.remove(request.user)
    else:
        user_profile.followers.add(request.user)
    return redirect('accounts:detail', account_pk)

movies/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import ReviewForm
from .models import Movie,Review
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies' : movies
    }
    return render(request,'movies/index.html',context)

def detail(request,movie_pk):
    movie = get_object_or_404(Movie,pk=movie_pk)
    review_form = ReviewForm()
    context = {
        'movie': movie,
        'review_form': review_form
    }
    return render(request,'movies/detail.html',context)

@require_POST
def new(request,movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie,pk=movie_pk)
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            form = review_form.save(commit=False)
            form.user = request.user
            form.movie = movie
            form.save()
            return redirect('movies:detail',movie_pk)
    else:
        return redirect('accounts:login')

@require_POST
def delete(request,movie_pk,review_pk):
    review = get_object_or_404(Review,pk=review_pk)
    if review.user == request.user:
        review.delete()
    return redirect('movies:detail',movie_pk)

@require_POST
def like(request,movie_pk):
    movie = get_object_or_404(Movie,pk=movie_pk)
    if request.user.is_authenticated:
        if request.user in movie.like_user.all():
            movie.like_user.remove(request.user)
        else:
            movie.like_user.add(request.user)
            
        return redirect('movies:detail', movie_pk)
    else:
        return redirect('accounts:login')

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="회원가입">
</form>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block body %}
<h1>유저 목록</h1>
<div class="container">
  {% for account in accounts %}
    <li>
      <a href="{% url 'accounts:detail' account.pk %}">{{ account.username }}</a>
    </li>
  {% endfor %}
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="로그인">
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <h1>{{ account.username }}님의 프로필
    {% with account.followers.all as followers %}
    <a href="{% url 'accounts:follow' account.pk %}">
      {% if user in followers %}
      팔로우 취소
      {% else %}
      팔로우
      {% endif %}
    </a>
    {% endwith %}
  </h1><br>
  <h2>작성한 평점</h2>
  {% for review in account.review_set.all %}
  <p>내용 : {{ review.content }}, 평점: {{ review.score }}</p>
  {% empty %}
  <h1>평점 정보가 없습니다.</h1>
  {% endfor %}
  <hr>
  <h2>좋아하는 영화</h2>
  {% for movie in accounts.like_movies.all %}
  <h3>
    {{ movie.title }}
  </h3>
  {% empty %}
  <h1>좋아하는 영화가 없습니다.</h1>
  {% endfor %}
  <hr>
  <h4>팔로워 <b>{{ account.followers.all.count }}</b> 팔로우 <b>{{ account.followings.all.count }}</b> </h4>
</div>
{% endblock %}

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block body %}
<img src="{{movie.poster_url}}" class='my-image'alt="">
<h1>{{movie.title}} 

</h1>
<h3>관객수 : {{movie.audience}} 장르 : {{movie.genre.name}}
</h3>
<h3>좋아요 : {{movie.like_user.all.count}} 
<form action="{% url 'movies:like' movie.pk %}" method='POST'>
{% csrf_token %}
<input type="submit" name="" value='좋아~!'>
</form>
</h3>
<p>{{movie.description}}</p>
<hr>
<p>
리뷰 부탁 드립니다.
<form action="{% url 'movies:new' movie.pk %}" method='POST'>
{% csrf_token %}
{{review_form}}
<input type="submit" value="등록">
</form>
</p>
<hr>
{% for review in movie.review_set.all %}
<p>{{review.user}} => 평점 : {{review.score}} 리뷰 : {{review.content}}
{% if user == review.user %}
 <form action="{% url 'movies:delete' movie.pk review.pk %}" method='POST'>
 {% csrf_token %}
 <input type="submit" value='리뷰 삭제'>
 </form>
 {% endif %}
 </p>
 <hr>
{% endfor %}
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% block body %}
{% for movie in movies %}
<a href="{% url 'movies:detail' movie.pk %}"><img src="{{movie.poster_url}}" class='my-image' alt=""></a>
{% endfor %}
{% endblock %}

pjt10/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>영화 그냥 프로젝트</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    .my-image {
      width: 250px;
      height: 400px;
    }
  </style>
</head>

<body>
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'movies:index' %}">홈</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:detail' user.pk %}">내 프로필</a>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
    </li>
    {% endif %}
  </ul>
  {% block body %}
  {% endblock  %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
</body>

</html>